import os
import secrets

from dotenv import load_dotenv

load_dotenv()

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")

# Shared secret guarding the public POST /widget/chat endpoint. When set,
# callers must send it in the X-API-Key header. When unset, the endpoint is
# left open (with a startup warning) so local dev isn't broken.
WIDGET_API_KEY = os.getenv("WIDGET_API_KEY")

PORTAL_ADMIN_USERNAME = os.getenv("PORTAL_ADMIN_USERNAME", "admin")
PORTAL_ADMIN_PASSWORD = os.getenv("PORTAL_ADMIN_PASSWORD", "")
PORTAL_SESSION_SECRET = os.getenv("PORTAL_SESSION_SECRET") or secrets.token_urlsafe(32)

# --- Knowledge base -------------------------------------------------------
# Generated by the site's build step and served with the site, so the bot and
# the page can never disagree about a price. Fetched once at startup; the
# committed snapshot in data/kb.txt covers a boot with no network.
KB_URL = os.getenv("KB_URL", "https://briqx.ninja/kb.txt")
KB_FETCH_TIMEOUT = float(os.getenv("KB_FETCH_TIMEOUT", "10"))

# --- Token management -----------------------------------------------------
# IMPORTANT: deepseek-v4-flash is a reasoning model. Its internal reasoning is
# billed and counted inside this same budget, and it can run to several hundred
# tokens before a single visible word is produced. Set this too low and the call
# terminates with finish_reason="length" mid-reasoning, returning EMPTY content —
# the visitor sees a blank bubble. Measured: a question needing deliberation used
# ~1400 chars of reasoning plus ~340 of answer (409 completion tokens).
# The 2-4 sentence limit is enforced by the prompt, not by this number.
MAX_OUTPUT_TOKENS = int(os.getenv("MAX_OUTPUT_TOKENS", "800"))

# Conversation window. Long history was the main silent token drain: every turn
# re-sent the whole 12-hour transcript. Keep just enough for a follow-up like
# "what about the second one?" to resolve.
HISTORY_TURNS = int(os.getenv("HISTORY_TURNS", "3"))
HISTORY_CHAR_CAP = int(os.getenv("HISTORY_CHAR_CAP", "1200"))

# Longest question we will forward. Anything above is rejected locally.
MAX_INPUT_CHARS = int(os.getenv("MAX_INPUT_CHARS", "600"))

# --- Spend protection -----------------------------------------------------
# Per-visitor throttle.
RATE_LIMIT_PER_MINUTE = int(os.getenv("RATE_LIMIT_PER_MINUTE", "8"))
RATE_LIMIT_PER_DAY = int(os.getenv("RATE_LIMIT_PER_DAY", "60"))

# Global circuit breaker. Rate limits are per-IP and a determined caller rotates
# IPs; this is the ceiling that actually bounds the bill. Once tripped, the
# widget serves published content and the WhatsApp handoff until midnight UTC.
DAILY_API_CALL_CAP = int(os.getenv("DAILY_API_CALL_CAP", "1500"))

# --- Human handoff --------------------------------------------------------
# WhatsApp is a person, deliberately — no bot on the other end. The visitor's
# question is prefilled so the conversation opens with what they asked.
WHATSAPP_NUMBER = os.getenv("WHATSAPP_NUMBER", "")
