"""The knowledge base, loaded once at startup.

Munyakazi answers from the briqx site's published content — generated by the site's
build step from the same file the page renders prices from, so the bot cannot quote a
price the page no longer shows.

Load order: fetch the live file, fall back to the committed snapshot. The snapshot
means a boot with no network still answers correctly, just possibly from an older
price sheet — `kb_is_stale()` reports which happened.

This module deliberately does NOT build the prompt. llm.py assembles the frozen
system block once at import; see the caching note there.
"""
from __future__ import annotations

import logging
from pathlib import Path

import httpx

from src.config import KB_FETCH_TIMEOUT, KB_URL

log = logging.getLogger(__name__)

SNAPSHOT_PATH = Path("data/kb.txt")

_MIN_PLAUSIBLE_CHARS = 200


def _load() -> tuple[str, bool]:
    """Return (kb_text, is_stale). Stale means the live fetch failed."""
    try:
        response = httpx.get(KB_URL, timeout=KB_FETCH_TIMEOUT)
        response.raise_for_status()
        text = response.text.strip()
        if len(text) < _MIN_PLAUSIBLE_CHARS:
            raise ValueError(f"kb.txt looks truncated ({len(text)} chars)")
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(text, encoding="utf-8")
        log.info("KB loaded from %s (%d chars)", KB_URL, len(text))
        return text, False
    except Exception as exc:
        log.warning("KB fetch from %s failed (%s) — falling back to snapshot", KB_URL, exc)

    if SNAPSHOT_PATH.exists():
        text = SNAPSHOT_PATH.read_text(encoding="utf-8").strip()
        log.warning("KB loaded from snapshot %s (%d chars) — may be stale", SNAPSHOT_PATH, len(text))
        return text, True

    raise RuntimeError(
        f"No knowledge base available: {KB_URL} unreachable and no snapshot at "
        f"{SNAPSHOT_PATH}. Run `npm run build:kb` in the site repo and copy "
        f"public/kb.txt to {SNAPSHOT_PATH}."
    )


_TEXT, _IS_STALE = _load()


def kb_text() -> str:
    return _TEXT


def kb_is_stale() -> bool:
    return _IS_STALE
